### ISSUE TITLE
[github]: missing topics

### ISSUE THREAD

**Issue by konhi** [deathau/markdownload#100]
This repository doesn't have topics such as `obsidian`, `obsidian-md`, `web-clipper`, `chrome-extension`, `firefox-extension` which causes less reach. Please add these topics, so users can easily find this great repository! 😊

**Comment by deathau** [comment]
Thanks. I've added some topics.
I'm not entirely sure about adding Obsidian as a topic though, as while it's quite useful for Obsidian, it's in no way Obsidian-specific.
