### ISSUE TITLE
Parameterize Title

### ISSUE THREAD

**Issue by bradonomics** [deathau/markdownload#109]
Is it possible to make the page title lowercase and add hyphens between the words? Something like Ruby's `parameterize` function? If not, is that something you'd be willing to add? Perhaps `{title:parameterize}`

**Comment by deathau** [comment]
This is a pretty good idea, so I've implemented it with multiple case options.
To use it, just append one of the following to any replacement values:
`:pascal` — PascalCase: every word capital
`:camel` — camelCase: every word capital except the first word
`:kebab` — kebab-case: hyphens between words, all lowercase (like the requested `parameterize`)
`:snake` — snake_case: underscores between words, all lowercase

![cases-template](https://user-images.githubusercontent.com/1421840/153805164-0b79380b-ab24-4ef4-bed8-89975aaaee8c.png)
![cases](https://user-images.githubusercontent.com/1421840/153805191-1cc94fa2-1a8f-4fca-b12c-4e9dcf3b11a2.png)
