### ISSUE TITLE
Download images linux

### ISSUE THREAD

**Issue by mvt-oviedo** [deathau/markdownload#112]
Great extension and good job,

But in linux systems there is one problem with download images and markdown code.

To view properly the downloaded images, it is necessary .md file at the same image directory and markdown code like ![](image) without image path.

Many thanks,

**Comment by deathau** [comment]
You can try clearing out the Image filename prefix template in the options to have the images download in the same folder as the .md
![image](https://user-images.githubusercontent.com/1421840/204960716-983a164c-de25-4a38-9c80-45e9039240dd.png)

And also change the image style to "Pure Markdown"
![image](https://user-images.githubusercontent.com/1421840/204960818-96983e32-844f-4278-89f9-78e1ed038a9d.png)
