### ISSUE TITLE
No folder called downloads on systems not english

### ISSUE THREAD

**Issue by kjelle392** [deathau/markdownload#126]
I run a norwegian version of Windows 10. There's no folder called "downloads" there (it's called "Nedlastninger"). Therefore the extensions fails to save the files.

There should be a way to point the extension to a spesific folder.  

The extensison seems useless for system other than english.

**Comment by deathau** [comment]
MarkDownload doesn't specifically point to a folder called "downloads", it doesn't (and _can't_) point to _any_ specific folder.
It simply downloads files wherever the browser is configured to download files.
Is there a particular issue you're having with the extension?

**Comment by kjelle392** [comment]
Okey, but where does toe files go then? I can't find them.

**Comment by deathau** [comment]
The files _should_ be going to the same spot as any other files you download in the browser...
I'm not sure about this, but you might be able to turn on the "Save As" option in the MarkDownload settings, and the folder that first appears in that window when you try to download next will likely be the folder everything else is saving in.

**Comment by kjelle392** [comment]
Ah now I understand! The "downloadfolder" is the browsers default downloadfolder, not the default one under Windows.
