### ISSUE TITLE
[Feature Request] Option to have base64 encoded images in-lined as references

### ISSUE THREAD

**Issue by ShawnCorey** [deathau/markdownload#128]
Thanks for adding the in lined image download option, really helps with note portability!

If there could be an option to have the images embedded as references, with the full base64 at the end of the clipped text that could help make the clipped notes "cleaner" when viewing the raw markdown. This doesn't make a difference when viewing the rendered markdown, just when going in and viewing/editing the raw text.

Current embedding style:
```
<note text>
[![Image Alt Text](data:image/png;base64,iVBORw...)]
<note text>
```
Propose option for something like:
```
<note text>
![Image1 Alt Text][<hash of image1 or other unique identifier>]
<note text>
![Image2 Alt Text][<hash of image2 or other unique identifier>]
...
<end of note text>

[<hash of image1 or other unique identifier>]:data:image/png;base64,iVBORw...

[<hash of image2 or other unique identifier>]:data:image/png;base64,iVBORw...
```

**Comment by deathau** [comment]
I looked at the turndown source for referenced links and implemented that for images (as an option). So whether you've got base64 images or not, as long as the link style isn't just stripped or obsidian related, you choose to output images as referenced.

The reference id is `'fig' + i` (where `i` is an auto-incrementing number), so you end up with something like
```markdown
<note text>
![Image1 Alt Text][fig1]
<note text>
![Image2 Alt Text][fig2]
...
<end of note text>

[fig1]: data:image/png;base64,iVBORw...

[fig2]: data:image/png;base64,iVBORw...
```

I've tested the output in VSCode (works fine), and Obsidian (had issues). Notably, Live Preview in Obsidian will not render these images, but it does work in reading view. Also, if there are a lot of base64 images (I was testing with [Wait But Why](https://waitbutwhy.com/2018/04/picking-career.html) it seems to lock up Obsidian trying to parse/render the reading view.
