### ISSUE TITLE
download with a incorrect file name

### ISSUE THREAD

**Issue by wenchengxucool** [deathau/markdownload#133]
I set {title}.md as file name. but it was downloaded as 'e3a35ecb-0c1b-4032-abfa-bbea0512b08d'. It has no .md in it.
Chrome  99.0.4844.51 (x86_64) macOS 12.3

**Comment by Issam-seghir** [comment]
Have the same problem here

**Comment by PawelWaw** [comment]
I have the same + not possible to save picturers in folders
Vivaldi/Edge/Chrome - latest builts
running on Windows 11 22H2
on two computers - desktop & laptop

**Comment by deathau** [comment]
This has cropped up for other users and it's an incompatibility with some other download extensions. I'm not sure exactly how to resolve this, but I'm tracking the issue in #10
