### ISSUE TITLE
[Feature Request] Shortcut to copy markdown style URL of a page

### ISSUE THREAD

**Issue by vortexmak** [deathau/markdownload#141]
Is there a way to have a shortcut to the "Copy tab URL as markdown link".

I do a lot of URL pasting to Obsidian and copying the tab URL is a three click process right now.

**Comment by desk7** [comment]
It has been already implemented! See https://github.com/deathau/markdownload/releases/tag/3.1.0 for that and other shortcuts.
<kbd>Alt</kbd> +<kbd>Shift</kbd>+<kbd>L</kbd> copies the current tabs URL as a markdown link to the clipboard.
