### ISSUE TITLE
Not Working on Selected Text With Headings

### ISSUE THREAD

**Issue by arandorion** [deathau/markdownload#148]
I've tried this on a few different pages, and if I select text that includes headings, the **Selected Text** tab does not behave properly. It will either display only the headings or it will repeat the same heading and text multiple times in a row. But it does not display the entire contents of the selection.

The **Entire Document** tab appears to be working normally.

[Here is a sample page to try](https://www.baeldung.com/linux/join-multiple-lines). Select some of the page and be sure to include both text and a couple of headings. Then go to the **Selected Text** tab of MarkDownload. That should behave as I described.

Any ideas about what's going on?

Thanks

MarkDownload 3.1.0
Firefox 102.0.1
macOS 10.15.7

**Comment by deathau** [comment]
Not entirely sure what's happening, but this appears to be the same as #33
