### ISSUE TITLE
Image file extension being appended to name without period separator

### ISSUE THREAD

**Issue by CharlieGB** [deathau/markdownload#163]
Version 3.2.1 on MacOS
Both on Firefox and Chrome.
Images are downloaded correctly, but the filename is changed from StatisticsFigure_1.png to StatisticsFigure_1png so they don't work correctly without the extension. The markdown file references the same renamed file without the extension.

**Comment by aancw** [comment]
I think it would be good if you explain the problem more details. Maybe with step by step how to produce it or with video screen? So, everyone can test and know what's the problem.

**Comment by CharlieGB** [comment]
I have worked out the issue. Apologies, it was only when I received your message that I looked through again.
I was stripping out '.' from the disallowed characters in the filename. It obviously is stripping out the extension period too.
If I take that out, it works as expected.

**Comment by CharlieGB** [comment]
Yes, I will close this as it works! However, I think one could consider the file extension separate to the main name for a future update? Thank you for all your support and the great extension.

**Comment by aancw** [comment]
That's would be great for future update.
