### ISSUE TITLE
Add toggle button for images

### ISSUE THREAD

**Issue by 1xPdd** [deathau/markdownload#164]
Hi, thanks for your add-on. One small tweak I would love to see is the possibility of turning on/off the image downloading on a case-by-case basis. Though I often don't want to download images, there are still many cases in which it would be ideal. Going into the settings to change this is a bit cumbersome. This could be done in the same in the same way the front/end template can be toggled on/off from the little pop-up window. Thanks!

**Comment by aancw** [comment]
Does it only place the url href for image by default, isn't?

**Comment by 1xPdd** [comment]
I'm not sure I recall the default. In the preferences, I have both "Downloads API (recommended)" and "Download images alongside markdown files" selected. Images are then downloaded and placed in a custom directory.

My request, however, was to be able to change this in the pop-up at the moment of save/clip, rather than, as is the current way, going into the settings. Sorry if that wasn't clear.
