### ISSUE TITLE
Obsidian Integration Problem

### ISSUE THREAD

**Issue by MagePrometheus** [deathau/markdownload#170]
Windows 10, Obsidian 15.9, Advanced URI 1.28.0 fully enabled.
Markdownload 3.2.1

I've tried as much as I can think of first.
Normal download to downloads folder works. Obsidian integration doesn't create a new MD file in the vault. Data is waiting on the clipboard.

It looks like a problem with forward slash / appended to the front of the filename instead of 2 backslashes for windows. \\
C:\\Projects\\Obsidian\\Technical/How to Take...md

Error in electron developer window:

Received URL action {vault: 'Technical', clipboard: 'true', mode: 'new', filepath: 'C:\\Projects\\Obsidian\\Technical/How to Take Smart Notes in Obsidian - by Josh Duffney', action: 'advanced-uri'}
app.js:1 Uncaught (in promise) Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at we (app.js:1:244125)
    at t.checkPath (app.js:1:970824)
    at t.<anonymous> (app.js:1:973485)
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at app.js:1:234120
    at new Promise (<anonymous>)
    at m (app.js:1:233865)
    at t.createFolder (app.js:1:973375)
    at AdvancedURI.eval (plugin:obsidian-advanced-uri:4427:61)

**Comment by merlinuwe** [comment]
Windows 10, Obsidian 15.9, Advanced URI 1.28.0 Markdownload 3.2.1 (I use Google Chrome)

I have the same problem - but are my settings correct (i. e. trailing slashes, ...)?

Obsidian Vault Name: 

Obsidian

Obsidian Folder:

H:\Syncthing\Obsidian

**Comment by aancw** [comment]
Hi, I already made change to the feature. It will automatically using \\ for windows and / for non windows. Please try it.

https://github.com/aancw/markdownload/commit/0975a15f960f847cf652e8df1958043f7e0c0a15

Step to try:

1. Clone my repo `git clone https://github.com/aancw/markdownload/ -b sendobsidian`
2. Enter the src folder `cd src`
3. Install web-ext `npm install --global web-ext` 
4. Run the web ext with `web-ext run --browser-console`

I will push the update when it's fixed on windows. Thank you for helping me.

**Comment by MagePrometheus** [comment]
I've tried testing this but after setting up the temp plugin for Obsidian integration the send to Obsidian options don't appear in the context menus. Sorry.

**Comment by aancw** [comment]
> I've tried testing this but after setting up the temp plugin for Obsidian integration the send to Obsidian options don't appear in the context menus. Sorry.

You need to enable in the extension preference. After you enable and input the right things, reload the extensions.

**Comment by MagePrometheus** [comment]
Thanks. I didn't unload/reload the plugin. Now I get:

Received URL action {vault: 'MasterVault', clipboard: 'true', mode: 'new', filepath: 'C:\\Projects\\Obsidian\\MasterVault\\Main Page', action: 'advanced-uri'}
app.js:1 Uncaught (in promise) Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at Pe (app.js:1:248253)
    at t.checkPath (app.js:1:1081963)
    at t.<anonymous> (app.js:1:1084624)
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at app.js:1:234243
    at new Promise (<anonymous>)
    at m (app.js:1:233988)
    at t.createFolder (app.js:1:1084514)
    at AdvancedURI.eval (plugin:obsidian-advanced-uri:4427:61)

So all the \\ look ok.

In obsidian-advanced-uri, function AdvancedURI.prototype.writeAndOpenFile(...) line number 4427 I set a break point and a watch on variables dir & outputFileName
dir: "c:/Projects/Obsidian/MasterVault"

this.app.vault.createFolder(dir) looks to be unhappy but I'm wondering why creatFolder is being called with the path to my vault.

This function call looks correct:
AdvancedURI.prototype.writeAndOpenFile = function (outputFileName, text, parameters)...

outputFileName: "c:/Projects/Obsidian/MasterVault/Main Page.md"
This looks ok as it was a text selection from the main page of Wikipedia.

Hope this helps.

**Comment by aancw** [comment]
I think I need to install obsidian and the extension on windows. Let me try.

What's url that you try to send/save to obsidian?

**Comment by aancw** [comment]
Hi, can you take a video record? I've tried in windows and no problem. Here is my video
[](https://streamable.com/zng6y3)

**Comment by MagePrometheus** [comment]
That video did the trick and it's working now.
The problem was me. I was putting the full path to my vault into the "Obsidian Folder" textbox under Enable Obsidian Integration. What I really needed was the MarkDownload Folder For Clips.

Sorry to cause you extra work.

**Comment by aancw** [comment]
I think i need to add help and example, so people are not confused with the name "Obsidian Folder"

**Comment by MagePrometheus** [comment]
For people like me who are retired. 😄 I did learn a lot about browser plugins and hot loading.
