### ISSUE TITLE
[Question]: Mechanism to generate slug from title

### ISSUE THREAD

**Issue by TSSlade** [deathau/markdownload#173]
Is there a way to take a title such as "Don't pay ridiculous amounts of money..." and cast it as e.g. "dont-pay-ridiculous"?

Something along the lines of [python-slugify](https://pypi.org/project/python-slugify/).

If so, how do we deploy it in the extension's options/settings?

**Comment by deathau** [comment]
The following is a screenshot from the Custom text information in the extension options:
![image](https://user-images.githubusercontent.com/1421840/204973407-7ac063ab-4e42-451d-8e8a-caf1e0c8fa99.png)
So in your case, you could do something like `{pageTitle:kebab}`. It won't trim the title like python-slugify might? But it will give you something like `dont-pay-ridiculous-amounts-of-money`
