### ISSUE TITLE
KaTeX math formulas are being stripped

### ISSUE THREAD

**Issue by mnaoumov** [deathau/markdownload#186]
Try to grab the content from the https://katex.org/

The KaTeX rendered formulas are not included in the result Markdown

![image](https://user-images.githubusercontent.com/735878/204634275-cf17803c-ba91-446e-a170-35908cab9b4d.png)

**Comment by bwnjnOEI** [comment]
On my Brave browser, some things don't work properly. For example, the formulas on [this blog ](https://ewintang.com/blog/2019/01/28/an-overview-of-quantum-inspired-sampling/)page cannot be parsed well and are missing `$$`. I checked its HTML header file and found that it includes Katex.
