### ISSUE TITLE
Copy tab as markdown link

### ISSUE THREAD

**Issue by sambbaron** [deathau/markdownload#19]
Sometimes I just need to collect a webpage link, and I want to get the browser tab as a markdown link with the title. Could that be added as an option to the tab context menu?

Also, I would want to use the tab title in the markdown link from `<meta name="title" content="...">`. It seems that what is being used as the article title is `<meta property="og:title" content="...">`. They are not always the same, and I prefer the tab title because it usually includes the website name. Perhaps there could be a new text replacement value for this.

**Comment by argenos** [comment]
I want to add a +1 to getting a Markdown-formatted link of the URL would be great. For now, I've been using [this addon](https://github.com/0x6b/copy-selection-as-markdown#usage) to copy the title and URL but I'd love to consolidate into one.

**Comment by deathau** [comment]
I've added this in (will be available next release). It uses the title/file name template from your options for the bit between the square brackets.
