### ISSUE TITLE
Code blocks with multiple sequential line breaks are captured without line breaks

### ISSUE THREAD

**Issue by mnaoumov** [deathau/markdownload#199]
Consider

`<pre class="language-text">line1<br><br><br><br></br>line2</pre>`

**Expected result**

````
```text
line1



line2
```
````

**Actual result**

````
```text
line1line2
```
````

**Comment by deathau** [comment]
🤔 Isn't the point of `<pre>` tags to preserve the code within?
I would expect `<pre class="language-text">line1<br><br><br><br></br>line2</pre>` to output as
~~~markdown
```text
line1<br><br><br><br></br>line2
```
~~~

if the following
```html
<pre class="language-text">
line 1



line 2
</pre>
```
is outputting as 
~~~markdown
```text
line1line2
```
~~~
... Then that _is_ an issue that needs fixing. I'll investigate further before I approve #200

**Comment by mnaoumov** [comment]
@deathau sorry but I think you expect from `pre` tag something that is not according to the spec
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

If you want to get `<br>`  text within `pre` you need to escape it: `<pre>&lt;br&gt;</pre>`

**Comment by deathau** [comment]
Yep, you're right. I did a quick test in chrome dev tools before posting and it output the `<br>` tags, but actually writing it in a html file shows that it makes them newlines. Sorry about that.
