### ISSUE TITLE
"Quick save button" - save file in default location

### ISSUE THREAD

**Issue by dxcore35** [deathau/markdownload#21]
**Feature request**

1. Add new button, quick save or something save explanatory
2. Add option to define default folder for saving
2. After clicking on "Quick save button" it will save the file without any prompt into location set in settings

---

**My user case:** Im using Obsidian, and all my new articles are going first into the ```🌱SEEDBOX``` folder. Later I'm going into folder and add appropriate tags and link the articles into MOC. With this option it will help to save time to move file from downloads... and in same time it will introduce the very useful concept of ``🌱SEEDBOX``` folder to bigger audience.

**Comment by deathau** [comment]
I've had this request a couple of times from a few places, but it's not something I know how to solve, unfortunately.

The browser only allows me to specify whether I should open the Save As modal, or stick with the browser default. And I don't have any access to the file system to list folders, let alone write to one. It's a potential security issue for the browser.

My suggestion would be to turn on the "Save As" option in the extension's settings. I _think_ it remembers the last selected folder, so it would only be one extra click 🤞. I agree it's not ideal, but I haven't got a better solution at the moment.

**Comment by dxcore35** [comment]
Just check this extension. it is doing it somehow. Maybe you can ask the devs of this extension. 

https://chrome.google.com/webstore/detail/dbjbempljhcmhlfpfacalomonjpalpko

So it is possible.

**Comment by deathau** [comment]
I'll look into it. Thanks for the lead

**Comment by deathau** [comment]
@dxcore35 I've had a look into this extension, and it looks like it's got the same limitations I'm talking about. It can download into a _subfolder_ of the downloads folder, but can't download anywhere outside of the downloads folder.

So for example, if your downloads folder is `~/downloads` and you specified you wanted to download to a folder called `🌱SEEDBOX`, then the downloaded files will end up in `~/downloads/🌱SEEDBOX`. This could work if you have set your browser's default downloads folder to be the same as your vault (or your vault lives inside of your downloads folder), but I don't think this is normal.

All that being said, specifying a subfolder for the notes probably isn't a bad idea (especially in relation to #22) so it's probably a worthwhile option to add.

**Comment by dxcore35** [comment]
I see.....

Can you execute some standard terminal scripts via extension?
I just thinking that if you have access to download folder, you can download it there first and then in old fashion way just execute move  command via terminal command.

**Comment by deathau** [comment]
Executing arbitrary terminal scripts would be an even bigger security risk than accessing the local file system, so I doubt there would be a way to do that. However, in the future, I could probably rig up an obsidian plugin which is able to do that and potentially have the extension trigger the obsidian plugin via custom URL to move the files into the vault.

It's all pretty pie-in-the-sky at the moment, but I'm definitely looking out for opportunities.  
And yea, it will help with the downloading images idea, thanks 👍

**Comment by dxcore35** [comment]
The plugin will more better idea! And I think more easy to do and with no restrictions....

**Comment by montemartin** [comment]
@dxcore35 check out [Organize](https://github.com/tfeldmann/organize). I use it for exactly this use case: moving files from `~/Downloads` to my Obsidian Inbox folder for later processing. I have MarkDownload configured with specific name format (`{date:YYYYMMDDHHMM}-{title}.bookmark`) and Organize is configured to only move files with that format.

**Comment by deathau** [comment]
@dxcore35 I've made a couple of updates that might help you (pending release)
- the title template should allow forward slashes so you can save to a subfolder of your download folder
- fixed #24 so you can use the keyboard shortcut (alt+shift+M) then enter to quickly download to that folder

**Comment by Gr-Nobel** [comment]
This thread is off for a while. I see a Obsidian integration option on the plugin manage page. Does the integration work.I have tried to use it but wasn't successfull.
