### ISSUE TITLE
Windows: Using a Symbolic Link to download clips into a Vault that is not under Downloads/

### ISSUE THREAD

**Issue by ichmoimeyo** [deathau/markdownload#213]
In Options under "**Downloads/**" I entered
**\_MarkDownload**

representing ... 
**C:\Users\ichmo\Downloads\\_MarkDownload**

I want to get my clips automatically into **my Vault**:
C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

**Symbolic Link in a nutshell** ...
mklink /J Link Target
mklink /J C:\LinkToFolder C:\Users\Name\OriginalFolder

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

I opened a Command Prompt window as Administrator & entered:

`mklink /J C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload C:\Users\ichmo\Downloads\_MarkDownload`

Command Prompt window output:

```
C:\Users\ichmo>mklink /J C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload C:\Users\ichmo\Downloads\_MarkDownload
Junction created for C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload <<===>> C:\Users\ichmo\Downloads\_MarkDownload
```
It is working very nicely thanks to **How-To Geek**:
[The Complete Guide to Creating Symbolic Links (aka Symlinks) on Windows](https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/)

PS: CAUTION - deleting files in either folder deletes it in the other.
I especially will try to remember to not delete files inadvertently in C:\Users\ichmo\Downloads\\_MarkDownload

**Comment by fmeres** [comment]
Nice. You could also just run a script to move the files to the Obsidian folder, and schedule it with Task Scheduler.

**Comment by ichmoimeyo** [comment]
@fmeres - thanks, good idea for doing things in bulk. 
The main point for me is that once set up, I don't have to deal with the file explorer. 
When using Obsidian, anything I clip with MarkDownload appears in my capture folder(z_capture / markdownload) where I can immediately process it further.

**Comment by ichmoimeyo** [comment]
> In Options under "**Downloads/**" I entered **_MarkDownload**
> 
> representing ... **C:\Users\ichmo\Downloads\_MarkDownload**
> 
> I want to get my clips automatically into **my Vault**: C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload
> 
> \\\\\\\\\\\\\\\\
> 
> **Symbolic Link in a nutshell** ... mklink /J Link Target mklink /J C:\LinkToFolder C:\Users\Name\OriginalFolder
> 
> \\\\\\\\\\\\\\\\
> 
> I opened a Command Prompt window as Administrator & entered:
> 
> `mklink /J C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload C:\Users\ichmo\Downloads\_MarkDownload`
> 
> Command Prompt window output:
> 
> ```
> C:\Users\ichmo>mklink /J C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload C:\Users\ichmo\Downloads\_MarkDownload
> Junction created for C:\Users\ichmo\OneDrive\Documents\Obsidian\O_ichmoimeyo\z_capture\markdownload <<===>> C:\Users\ichmo\Downloads\_MarkDownload
> ```
> 
> It is working very nicely thanks to **How-To Geek**: [The Complete Guide to Creating Symbolic Links (aka Symlinks) on Windows](https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/)
> 
> PS: CAUTION - deleting files in either folder deletes it in the other. I especially will try to remember to not delete files inadvertently in C:\Users\ichmo\Downloads\_MarkDownload

**Comment by ichmoimeyo** [comment]
closed in error

The symbolic link topic was previously well answered ...
https://forum.obsidian.md/t/markdownload-markdown-web-clipper/173/136

**Comment by ichmoimeyo** [comment]
thanks to [CharisLee](https://github.com/CharisLee) ->  https://github.com/deathau/markdownload/issues/208#issuecomment-1435833395 got it working now without a symbolic link.
