### ISSUE TITLE
No Extension shortcuts for Obsidian integratoin commands

### ISSUE THREAD

**Issue by Guanine** [deathau/markdownload#222]
Love this extension, especially how well it integrates with Obsidian. ❤️
I was hoping to assign keyboard shortcuts to these commands

- Send Text selection to Obsidian 
- Send Tab to Obsidian

But these are not available under Extension Shortcut section.
Would you please make these available as well.

Thanks again for the incredible extension!!

![Screenshot 2023-03-26 at 2 20 20 PM](https://user-images.githubusercontent.com/96883830/227805514-7ad182e9-2b80-42ec-af39-5968cdec47f4.jpeg)
![Screenshot 2023-03-26 at 2 24 11 PM](https://user-images.githubusercontent.com/96883830/227805515-e9cd892a-0820-487a-9819-e0970f985c14.jpeg)

**Comment by joeynotjoe** [comment]
I just came to find out why I couldn't figure out how to make this work. I am seconding the desire to have a shortcut to send the tab (or text) to Obsidian. And I'll also second that this extension is amazing, thanks already for the terrific work!

**Comment by jordanstreiff** [comment]
#254 should resolve this, just needs to be merged.
