### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by spiritualgeek** [deathau/markdownload#233]

**Comment by Grant837** [comment]
I am starting to fear so.

**Comment by LightTemplar** [comment]
There is his commin on Jan. 25, 2023: https://github.com/deathau/markdownload/commit/27a316da1671747c00a7913787655533519c1232

**Comment by luispuerto** [comment]
I also fear that this project is abandoned since the last changes haven't been updated on the safari extension and therefore you can connect with obsidian properly…

**Comment by Grant837** [comment]
This demonstrates one of the down sides of Obsidian and it’s dependence on plugins….

**Comment by LightTemplar** [comment]
> This demonstrates one of the down sides of Obsidian and it’s dependence on plugins….

There is no many alternatives, I would say. At least, this is markdown and there is always some better or worse workarounds, so we could continue our personal works.

**Comment by spiritualgeek** [comment]
> This demonstrates one of the down sides of Obsidian and it’s dependence on plugins….

I wish the Obsidian team would consider this core to their offering, as any decent note-taking tool has a Chrome extension for performing snippets. A plea to the [Obsidian.md](https://github.com/obsidianmd) team.

For now, I'm reduced to using popclip together with a hobbled macOS shortcut driven by Actions for Obsidian, but it's really not that great

**Comment by spiritualgeek** [comment]
Considering the project to be abandoned, so I'm closing the issue
