### ISSUE TITLE
Add visual styling for current focus in dialogs and to confirm download

### ISSUE THREAD

**Issue by montemartin** [deathau/markdownload#24]
It would be helpful to have more distinct visual styling of the current focus inside the dialog window. I like to tab into the note, edit it, and then tab out > enter to download without using the mouse. Right now when the dialog opens there is no indication of what is currently in focus. It might also be helpful to have it start focused on the download button. This would help with the "quick save" part of #21. Once opened the note could be downloaded quickly by pressing enter without any additional tabbing. 

Additionally, because the dialog stays open after a download there is no way to tell when the file was sucessfully downloaded. Thankfully on Mac the download icon does bounce once to show a new download, but I still end with several copies sometimes. It would be nice if there were a visual change to indicate the file was downloaded.

**Comment by deathau** [comment]
Very good points. Will incorporate 👍

**Comment by deathau** [comment]
I added an indicator of focus and auto-focus on the download button as suggested (for next release).
The styling's a little bit ugly right now (IMO), but I think I need to do a pass and prettify everything anyway.

![image](https://user-images.githubusercontent.com/1421840/97268401-f7120a80-187f-11eb-9b6f-db72f098be9e.png)

For now I've also made the popup close when the download is triggered. Not 100% sure if this is desirable, but it seems to make sense for a quick-save: `ctrl+shift+M`, `enter` and your file is saved and the popup gone so you can get back to what you were doing.

**Comment by montemartin** [comment]
This is terrific. Closing on download is exactly the functionality I would expect. 

I'm happy to help clean up some of the visuals if you're open to a PR. I've never worked on a browser plugin so I took a quick look through the Firefox docs. I was able to get it operating as a local extension, but when I "Inspect" the extension it opens in a tab with no connect and the popup just loads the spinner and it's too late at night for me to do anymore debugging.

**Comment by deathau** [comment]
I haven't found a way to inspect the popup HTML elements (granted, I haven't looked very hard either).

Most things are in popup.html and popup.css in the [popup folder](https://github.com/deathau/markdownload/tree/master/popup), but if you also wanted to take a look at the options, they're similarly in the [options folder](https://github.com/deathau/markdownload/tree/master/options)

You might consider doing what I do and installing `web-ext` as well. I just run `web-ext run` from the extension folder and it boots up firefox with the extension set up. Then go to `about:debugging`, go to "this firefox" and you can inspect the background scripts from there.

If you do get it cleaned up, I'd be happy to accept a PR. I've paid practically no attention to how it looks so far 😅

**Comment by Kilohertz77** [comment]
It's not important enough to open an Issue for, but right now I'm unable to tab to the download button after I've tabbed into the textarea to change something. Pressing tab cycles between the title and the text, not the button.
