### ISSUE TITLE
The file name setting not working , is just like messy code

### ISSUE THREAD

**Issue by msskaa12** [deathau/markdownload#256]
I had setting the filename as "{pageTitle}.md" of extension  options , but when I go to donwload folder , I just see messy code like bellow,

e9aa2bea-155b-45b2-99d8-55c3ce8712b1
7a3c3406-9934-4267-a717-ce8133d91d23
6b8866af-72d7-477b-8551-65a9123efc7d

no file name，no extension

I use chrome on ubuntu 20.04.

anyone can help ，appreciate 

![image](https://github.com/deathau/markdownload/assets/78275037/8789c85e-10c7-460d-8cd1-74de80be8217)

![image](https://github.com/deathau/markdownload/assets/78275037/857615ad-fb4b-4788-a787-ab972ab2f891)

![image](https://github.com/deathau/markdownload/assets/78275037/7e0c9cc2-13fd-4a11-8fdc-ca6e2f839f3a)

**Comment by dalianzhu** [comment]
I have the same issue, could you tell me how to solve this?
