### ISSUE TITLE
Markdownload won't load in Brave

### ISSUE THREAD

**Issue by theesp** [deathau/markdownload#28]
I use the extension on Linux Mint Ulyana in both Brave (standard browser) and Firefox. It runs well on Firefox but has stopped working on Brave. When I click on the icon, the rectangular window opens and the 'busy' signal keeps on forever. No text appears in the window - nothing. By clicking outside the rectangular window it closes but no download.
It *did* work and I have tried most options switching on/off but no dice and I'd appreciate some guidance. TIA

**Comment by deathau** [comment]
Can you check if you get any errors in the developer console? 

First check the page one by right-clicking anywhere on the page, choosing "inspect element", then in the developer tools that pop up, switch to the Console tab. Try opening the extension via the icon again and see if any errors appear.

Similarly, see if you can see any errors in the background page by opening up `brave://extensions/`, turn developer mode on at the top right, click on the "background page" link for MarkDownload and again going to the console tab. Then in the main window, go any webpage and try opening the extension via the button and see if any errors pop up in that background console.

(apologies if this is too much detail, I don't have any way of knowing how much of that you already know 😅)

I downloaded Brave on Windows and it seemed to be fine, but I don't have any Linux machines to test there. I'm hoping there's an error in the console I can work with 🤞

**Comment by theesp** [comment]
Hi, thanks for your message and trouble. This is what I see in console when trying to markdownload the frontpage of the NYT:

www.nytimes.com/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.o.onreadystatechange (www.nytimes.com/:172)
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ inpage.js:1
main-e3ed66276bf94e2319cf.js:33 
(unknown) et2 snippet should only load once per page
(anonymous)
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ inpage.js:1
(index):1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
home-21a4fbbc33e533d1c651.js:1 [interactive] run: 100000007024018
vhs.min.js:1 vhs For complete VHS debug info: localStorage.debug = 'vhs*'
main-e3ed66276bf94e2319cf.js:33 Unhandled Promise Rejection (unhandledrejection): Error: SyntaxError: Unexpected end of JSON input
    at main-e3ed66276bf94e2319cf.js:67
(anonymous) @ main-e3ed66276bf94e2319cf.js:33
vhs.min.js:1 vhs For complete VHS debug info: localStorage.debug = 'vhs*'
www.nytimes.com/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.a.onload (<anonymous>:1:462)
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
home-21a4fbbc33e533d1c651.js:1 [interactive] stash: 100000007342981
home-21a4fbbc33e533d1c651.js:1 [interactive] stash: 100000007424663
home-21a4fbbc33e533d1c651.js:1 [interactive] stash: 100000007024018
home-21a4fbbc33e533d1c651.js:1 [interactive] remount: 100000007342981
home-21a4fbbc33e533d1c651.js:1 [interactive] remount: 100000007424663
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/runtime~adslot-4423b66a686225b0de4c.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/adslot-71d90833b72a88fcc3c9.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/runtime~main-e711fb2fd4484e5f3a2c.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendor-b414d56d6af1f806e64b.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/home-21a4fbbc33e533d1c651.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/main-e3ed66276bf94e2319cf.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://static01.nyt.com/elections-assets/2020/assets/48f81a/js/default/embeds/spotlight-footer.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://hgmhmanijnjhaffoampdlllchpolkdnj/js/lib/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendors~audio~capsule~collections~home~liveblog~paidpost~regionCapsule~story~trending~video-6da672789941ef94147d.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendors~audio~capsule~collections~home~liveblog~paidpost~regionCapsule~story~video-8b8a9fe47b1c4a0bda92.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendors~audio~byline~capsule~collections~customElectionsGuide~home~liveblog~paidpost~regionCapsule~s~50ba78f1-df327c32780b2c829377.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://pcmpcfapbekmbjjkdalcgopdkipoggdi/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/programmables-6c5d5d0975ce2535c27f.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Thanks

**Comment by theesp** [comment]
Hi, thank you for your reaction and troubles. This is what I see in console whe trying to markdownload the frontpage of the NYT:

www.nytimes.com/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.o.onreadystatechange (www.nytimes.com/:172)
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ inpage.js:1
main-e3ed66276bf94e2319cf.js:33 
(unknown) et2 snippet should only load once per page
(anonymous)
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ inpage.js:1
(index):1 [Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323
home-21a4fbbc33e533d1c651.js:1 [interactive] run: 100000007024018
vhs.min.js:1 vhs For complete VHS debug info: localStorage.debug = 'vhs*'
main-e3ed66276bf94e2319cf.js:33 Unhandled Promise Rejection (unhandledrejection): Error: SyntaxError: Unexpected end of JSON input
    at main-e3ed66276bf94e2319cf.js:67
(anonymous) @ main-e3ed66276bf94e2319cf.js:33
vhs.min.js:1 vhs For complete VHS debug info: localStorage.debug = 'vhs*'
www.nytimes.com/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.a.onload (<anonymous>:1:462)
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
home-21a4fbbc33e533d1c651.js:1 [interactive] stash: 100000007342981
home-21a4fbbc33e533d1c651.js:1 [interactive] stash: 100000007424663
home-21a4fbbc33e533d1c651.js:1 [interactive] stash: 100000007024018
home-21a4fbbc33e533d1c651.js:1 [interactive] remount: 100000007342981
home-21a4fbbc33e533d1c651.js:1 [interactive] remount: 100000007424663
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/runtime~adslot-4423b66a686225b0de4c.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/adslot-71d90833b72a88fcc3c9.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/runtime~main-e711fb2fd4484e5f3a2c.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendor-b414d56d6af1f806e64b.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/home-21a4fbbc33e533d1c651.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/main-e3ed66276bf94e2319cf.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://static01.nyt.com/elections-assets/2020/assets/48f81a/js/default/embeds/spotlight-footer.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://hgmhmanijnjhaffoampdlllchpolkdnj/js/lib/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendors~audio~capsule~collections~home~liveblog~paidpost~regionCapsule~story~trending~video-6da672789941ef94147d.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendors~audio~capsule~collections~home~liveblog~paidpost~regionCapsule~story~video-8b8a9fe47b1c4a0bda92.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/vendors~audio~byline~capsule~collections~customElectionsGuide~home~liveblog~paidpost~regionCapsule~s~50ba78f1-df327c32780b2c829377.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://pcmpcfapbekmbjjkdalcgopdkipoggdi/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://www.nytimes.com/vi-assets/static-assets/programmables-6c5d5d0975ce2535c27f.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Thanks

**Comment by deathau** [comment]
Unfortunately, it looks like most (if not all) of those errors are coming from the NYT page itself, and not from my plugin.
Could you perhaps try again on something like https://publish.obsidian.md/death-au/development/MarkDownload (because I can see there are no console errors there 😉)

**Comment by theesp** [comment]
Hi,

Thank you for your troubles - this is what I get on your Obsedian page:

DevTools failed to load SourceMap: Could not load content for
chrome-extension://hgmhmanijnjhaffoampdlllchpolkdnj/js/lib/purify.min.js.map:
HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

Thanks,

Thees Peereboom
independent M&A adviser for media/tech organisations
& provider of second opinions

**Comment by deathau** [comment]
🤔 that's still only the warnings from that page and not the extension.

I wonder if there's anything internal... See if you can see any errors in the background page by opening up brave://extensions/, turn developer mode on at the top right, click on the "background page" link for MarkDownload and again going to the console tab.  

Then in the main window, go any webpage and try opening the extension via the button and see if any errors pop up in that background console.

**Comment by theesp** [comment]
This is what I get:

Uncaught (in promise) TypeError: title.replaceAll is not a function
    at generateValidFileName (background.js:138)
    at background.js:466
    at Array.map (<anonymous>)
    at formatTitle (background.js:466)
    at async downloadMarkdownFromContext (background.js:474)

Thanks (again)

Thees Peereboom
independent M&A adviser for media/tech organisations
& provider of second opinions


m +3165 438 6747|www.asecondopinion.nl|@tpeereboom |onename.com/theesp |
telegram: theesp

'a spectator sees more than a player' <http://www.asecondopinion.nl/> so
follow me on twitter <http://www.twitter.com/tpeereboom>

**Comment by A-Tan5** [comment]
Try this, at least it works for me!

Setting -> Extensions -> Manage Extensions -> MarkDownload -> Allow access to file URLs -> just turn it on.

**Comment by theesp** [comment]
Thank you! It works (again).
