### ISSUE TITLE
If not "Always show Save As dialog", images are not downloaded with .md

### ISSUE THREAD

**Issue by No3371** [deathau/markdownload#34]
> Firefox 83.0, Win 10

Also, when using "Always show Save As dialog", images are not saved at path relative to .md

**Comment by deathau** [comment]
Can you provide the website that the images aren't downloading on for an example? It seems to be working for me on Firefox 84.0.1, Win 10.

For the save as issue... I've been playing around with it, and it seems no matter where you choose to download your md file, the images (any file not using a saveAs dialog) is limited to being saved in a subfolder of the downloads. I tried using absolute paths and relative paths using back-references `../` but the browser didn't allow any of it.

**Comment by No3371** [comment]
Yes, the save as behavior you described match my observation.
I was new to this plugin and very confused by some websites I was actively visiting, the issue of images not getting downloaded is not related to "save as" at all 😅 
I've now concluded it's still a interlink issue, in [this webpage](https://www.sigure.tw/learn-japanese/mix/difference/naide-nakute.php), the only image there is `<img src="/image/different/naide-nakute.png?v1">`, images without full url like this will not be downloaded.

**Comment by deathau** [comment]
Ah, in that case it must be related to #36

Thanks, I'll look into it

**Comment by No3371** [comment]
As the original described issue is my misunderstanding, I'm ok to close this, but not sure if you want to keep track of the "save as location" issue, so I'll leave this to you.
