### ISSUE TITLE
This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions.

### ISSUE THREAD

**Issue by sjhsbhqf** [deathau/markdownload#344]
Is there any desire for developers to adapt manifest v3?

![image](https://github.com/user-attachments/assets/aa98cf13-78fa-47c3-a557-43144963d937)

**Comment by SamejSpenser** [comment]
Have you checked this out? :thinking: 

“[Markdownload's future #342](https://github.com/deathau/markdownload/discussions/342)”

**Comment by sjhsbhqf** [comment]
> Have you checked this out? 🤔你检查过这个吗？ 🤔
> 
> “[Markdownload's future #342](https://github.com/deathau/markdownload/discussions/342)”“ [Markdownload的未来#342](https://github.com/deathau/markdownload/discussions/342) ”

Thanks
