### ISSUE TITLE
Converted Markdown keeps local path for links

### ISSUE THREAD

**Issue by No3371** [deathau/markdownload#36]
This section will be converted to the following markdown, it seems the links are invalid for markdown form in any means.

![圖片](https://user-images.githubusercontent.com/1814971/99513285-697c9300-29c5-11eb-8be0-4e9077304572.png)

```
かならず‐しも【必ずしも】

の解説

--------------------

［副］《「し」は副助詞、「も」は係助詞》打消しの語を伴って、必ず…というわけではない、…とは限らない、という気持ちを表す。「金持ちが必ずしも幸福ではない」「必ずしもそうとはいえない」

[「かならず【必ず】」の全ての意味を見る](/word/%E5%BF%85%E3%81%9A/#jn-43571)

類語

-   [あながち](/word/%E5%BC%B7%E3%81%A1/#jn-5381)
-   [まんざら](/word/%E6%BA%80%E6%9B%B4/#jn-210389)
```

**Comment by deathau** [comment]
Could you provide a link to this webpage so I can have a look?

**Comment by No3371** [comment]
https://dictionary.goo.ne.jp/word/%E5%BF%85%E3%81%9A%E3%81%97%E3%82%82/

The problem here is it just takes the url from html, which should be expected? But internal links like this are not useful for markdown and needs to be manually revised.
`<a href="/word/%E5%BF%85%E3%81%9A/#jn-43571"></a>`

**Comment by No3371** [comment]
The latest update landed on my browser this morning, local urls are gone, love it, thanks!
