### ISSUE TITLE
Intergration doesn't work

### ISSUE THREAD

**Issue by HyperSane** [deathau/markdownload#360]
It didn't tell me that I had to use right-click and hit send to tab.

Now it won't download images, have tried every setting multiple times, even checked afterwards using AI and it said it should be working according to config file.

This is what I get whenever it doesn't download images

# Internal Embed:

![image](https://github.com/user-attachments/assets/e6f3017c-fbc4-4faf-8c0b-7a9b05ca00fb)

All the options that are related to downloading - just give a broken link.

If I use the settings that just embeds it - it works.

I've spent so much time dealing with this, beyond frustrating and not detailed enough.

# Download API Just gives embedded link

![image](https://github.com/user-attachments/assets/f49056ca-475d-4487-bccf-e7550140c58e)

Doesn't actually download anything - works exactly like linking anything.

# Settings all do the same thing

All these settings give the exact same results

![image](https://github.com/user-attachments/assets/1618f446-e364-421c-bebc-0eab55de6200)

## ALL

The settings just link, I've tried them all.

Same result:

![image](https://github.com/user-attachments/assets/462d6709-18f1-44dc-95d8-6079b4d91237)

**Comment by SamejSpenser** [comment]
I usually don't use MarkDownload to download image files from the captures I make, but I remember using it that way in the past, so I decided to give it a test.

<p>&nbsp;</p>

**1\. Capture directory**

![A directory with the same name as the note I'm capturing](https://i.ibb.co/34WwPyt/25c52aa5-e45b-4db6-8b93-788b733a8cf3.jpg)  
I opened a text similar to what you showed in your screenshot and changed the MarkDownload settings to download the images into a directory with the same name as the note I'm capturing.

<p>&nbsp;</p>

**2\. Obsidian style**

![Use images in the Obsidian style (mentioning the image directory)](https://i.ibb.co/yFfvH40/b1631272-7d78-4b16-94bb-100ac8cfe27f.jpg)  
Then, I set it up to use images in the Obsidian style (mentioning the image directory).

<p>&nbsp;</p>

**3\. Checking downloads**

![Checked that all the image files were properly downloaded in the configured directory](https://i.ibb.co/278FpgX/60493701-5b75-4fa6-8bd3-767f82fa48d3.jpg)  
I captured the [Wikipedia article](https://en.wikipedia.org/wiki/Cultural_depictions_of_lions) and checked that all the image files were properly downloaded in the configured directory.

<p>&nbsp;</p>

**4\. Capture &amp; downloads checked in Obsidian**

![Both captured correctly](https://i.ibb.co/GCC4xCC/603afb88-4de3-4441-8041-3d31df89e8e6.jpg)  
In Obsidian, I found the directory and the captured note, both captured correctly.

<p>&nbsp;</p>

**5\. The images were added correctly in the configured format**

![The images were added correctly in the configured format](https://i.ibb.co/Zxm7HCP/357c77ce-34a5-4710-af2e-296c6133df12.jpg)  
When I checked the editing mode in Obsidian (I don't use Live Preview mode), I could see that the images were added correctly in the configured format…

<p>&nbsp;</p>

**6\. Wrapped in a redirect link to the media**

![Wrapped in a redirect link to the media](https://i.ibb.co/j3KJrqT/0ff95578-6ffd-412e-8740-3c5ccdfb64f1.jpg)  
And, even more, wrapped in a redirect link to the media, just like the standard on Wikipedia! 😉

<p>&nbsp;</p>

**7\. MarkDownload is properly set up with Obsidian**

![Is properly set up with Obsidian](https://i.ibb.co/GkL4HPm/0f31cf49-ae60-4726-a304-ad3ed041ad56.jpg)  
Here I'm using the GNU/Linux ArcoLinux (Qtile) distro, the LibreWolf browser, and MarkDownload is properly set up with Obsidian!

<p>&nbsp;</p>

***

<p>&nbsp;</p>

Sorry for any mistakes in my English; my native language is Brazilian Portuguese and I don't speak English very well, so I might have made some errors! 😅
