### ISSUE TITLE
Feature request: Download files in Downloads/MarkDownload/ folder

### ISSUE THREAD

**Issue by nikiluk** [deathau/markdownload#41]
To increase the usability and speed of bookmarking, custom download folder where all MD downloads will be stored is extremely useful. By default it could be something like `MarkDownload` or `MDClips` stored in the default browser's `Downloads` folder.

For example, Obsidian.md uses folders as vaults. This is useful as could be directly integrated in Obsidian.md or transferred without having to search and select for MD files and their resource folders each time.

**Comment by deathau** [comment]
You can achieve something like this by adding slashes into your title template (e.g. `MarkDownload/{title}`).

Other than that, I can't make downloads happen outside the default downloads folder without using the SaveAs dialog

**Comment by deathau** [comment]
The PR for this was merged in and the functionality is available in 3.0.0

**Comment by nikiluk** [comment]
@deathau I'm observing issues when downloading images, the download is initiated, but always fails. Will investigate this when I have a bit of time
