### ISSUE TITLE
bug: Download image files at wrong place 

### ISSUE THREAD

**Issue by jiangaq** [deathau/markdownload#43]
If specify a folder to download .md and all relatively images, the .md file can be downloaded at right place, while images will be downloaded in the default DOWNLOAD folder (im using Big Sur with chrome @ latest version), please check, thank you!

**Comment by omerdn1** [comment]
@jiangaq any reason why this was closed? This seems to be the behaviour from my point of view.
I know the chrome API doesn't like downloading files to folders other than the download folder so it might be the case that this is not a bug, just a limitation.

@deathau - any idea?
