### ISSUE TITLE
Additional uneccessary characters appear in markdown output

### ISSUE THREAD

**Issue by cydnax** [deathau/markdownload#50]
Additional backslash characters are added to underscores in the markdown output . Each `_` is replaced with `\_`.

Example:
Source:
tp_fan /proc/acpi/ibm/fan
hwmon /sys/class/thermal/thermal_zone0/temp

Markdownload markdown result:
tp\_fan /proc/acpi/ibm/fan 
hwmon /sys/class/thermal/thermal\_zone0/temp

Browser: Firefox Linux 85.0

**Comment by deathau** [comment]
There's more than just underscores at work here, turndown escapes a lot of things. Here is their explanation: https://github.com/domchristie/turndown#escaping-markdown-characters
> Turndown uses backslashes (`\`) to escape Markdown characters in the HTML input. This ensures that these characters are not interpreted as Markdown when the output is compiled back to HTML. For example, the contents of `<h1>1. Hello world</h1>` needs to be escaped to `1\. Hello world`, otherwise it will be interpreted as a list item rather than a heading.
> 
> To avoid the complexity and the performance implications of parsing the content of every HTML element as Markdown, Turndown uses a group of regular expressions to escape potential Markdown syntax. As a result, the escaping rules can be quite aggressive.

I'm not sure how to best resolve this. I could provide a custom override of the escape function, but it seems complex...

**Comment by deathau** [comment]
There's now an option to disable the turndown escaping, which should prevent underscores, etc being escaped.

Let me know if you have issues with it, but for now this issue is closed
