### ISSUE TITLE
[Feature Request] Can i please have {keywords} tag?

### ISSUE THREAD

**Issue by Offerel** [deathau/markdownload#51]
For using in Front Matter, I wish, I could have an extract of keywords. So that` <meta name="keywords" content="KeePass, Password, Safe, Manager, Database, Secure, Security, Open, Source, Code, Free, Encryption, Key, Master" />` would become `KeePass, Password, Safe, Manager, Database, Secure, Security, Open, Source, Code, Free, Encryption, Key, Master"`. Since personally, I separate Keywords only by space, it would be nice to have an option to remove additionally the comma. I know, this isn't ideal for all, but it would be nice for my workflow.

**Comment by Offerel** [comment]
I have made a new commit https://github.com/Offerel/roundcube_primitivenotes/commit/38f6f1c26535f5ec9c5dda173dcc766bd39b61b0 for my Roundcube Plugin. You can paste the Markdown from your plugin in to the editor. If a YAML header is found, it will autofill most of the other fields in the editor like author, date, source and title. I have added also a placeholder for the Keywords. If the keywords are available in your Extension, i will work my implementation. I really love this workflow.

Additionally, I have implemented a basic Turndown Service. If you paste selected text from within a browser, it will convert tis automatically to Markdown on pasting. This time without autofill other fields, because I have no idea how to capture and transfer all the other values from the source page. This only meant for browser instance, where i cant install your Extension.

**Comment by deathau** [comment]
Keywords is available in 3.0.0 (and you can specify your own separator).
Also, any other arbitrary meta tags (though without the custom seperator stuff).

Thanks for the suggestion!
