### ISSUE TITLE
Hidden charakters in Obsidian in downloaded .md file

### ISSUE THREAD

**Issue by highnze** [deathau/markdownload#53]
Hello 
The download works fine. I can open the .md file in Atom an there is nothing wrong with it. When it is opened in Obsidian the Preview-Mode works absoluty fine, but when I switch to the Edit-Mode suddenly there are everywhere small red dots. When I am hovering over them \uad appears. Can anyone help me? 

macOS 10.15.7
Firefox 85.0
Markdown 2.4.1
Obsidian v0.10.13
Atom 1.54.0

**Comment by deathau** [comment]
Does this happen with every site you clip, or just a few? Could you provide me a link to a site that is producing this behaviour?
I think I have an idea what the issue might be, but want to check out an example so I know any potential fixes work

**Comment by highnze** [comment]
I clipped some more and it just happens to this one
https://epaper.zeit.de/article/3a9b64701a8198e8fc07d86aabc5cdba858311babe8471f76f8207e13bdf90be
Articles from the normal homepage are working fine (e.g. https://www.zeit.de/gesellschaft/2021-02/klassismus-soziale-gruppen-soziologie-literatur-gesellschaft)

**Comment by highnze** [comment]
The Add-on can not pull the data of this site www.dezeen.com e.g. https://www.dezeen.com/2018/07/04/personal-data-could-be-a-vital-tool-in-designing-our-cities/
