### ISSUE TITLE
Code block comments ('#', '//') are not transferred through

### ISSUE THREAD

**Issue by omerdn1** [deathau/markdownload#55]
Hey bud, found out about this library yesterday and I love it!

One thing I noticed is that comments in code blocks are not being transferred to the downloaded md file.

For example, this code block:
```js
// import socket class
import Socket from '../socket';
```

Will give this output:
```js

import Socket from '../socket';
```

---

Another thing that I noticed is that the language type is also not transferred (e.g: js, yaml, etc..). I don't know if it's something that is easy to implement but it will definitely be a neat addition

Thanks!

**Comment by deathau** [comment]
So, here's a thing. If I try and use markdownload to get the text from your post there, I _do_ get the comments, but I _don't_ actually get it as a code block. Not sure why 🤔 

In the meantime, could you provide me with a link to a different page to test with where you _are_ getting code blocks but are losing comments?

**Comment by omerdn1** [comment]
@deathau Interesting, I'll play around with the code block extraction feature more today to see if I can zero in on the issue.
This is the link I used: https://snassr.io/post/0002_goreactsockets/

**Comment by jeffkimbrel** [comment]
Hi, just wanted to say this is still an issue. Comments or any lines in code blocks starting with `#` are still not coming through. If there are multiple, the first comes through but not the subsequent one or the rest of the line. 

I was trying on this page: https://www.nicholas-ollberding.com/post/wrench-normalization-for-sparse-microbiome-data/

**Comment by deathau** [comment]
I think I might've fixed this by adding better support for `pre` as code blocks in this commit: https://github.com/deathau/markdownload/commit/5fb11ae8cf2afff94bb710f19c47268ad56ce646
