### ISSUE TITLE
Certain content selected can not be converted to markdown (preview stuck at spinning)

### ISSUE THREAD

**Issue by No3371** [deathau/markdownload#57]
Take [this page](https://dictionary.goo.ne.jp/word/%E6%88%91%E3%81%8C%E5%84%98/) for example, if I just click the M button (whole page convert), it works:
![圖片](https://user-images.githubusercontent.com/1814971/108619106-b86f1400-745d-11eb-9397-0bf1d9d6bf17.png)

But if I make selection and this segment is included:
![圖片](https://user-images.githubusercontent.com/1814971/108619136-db012d00-745d-11eb-9336-ddd61b8558d6.png)
The preview window will stuck at loading:
![圖片](https://user-images.githubusercontent.com/1814971/108619165-e7858580-745d-11eb-95f7-9b2c5197d9fb.png)

It works when either the upper and the lower part is selected:
![圖片](https://user-images.githubusercontent.com/1814971/108619197-156aca00-745e-11eb-8506-043edc9d169b.png)

So it must be the middle part is not usable by the plugin, when selected.

**Comment by No3371** [comment]
BTW this is introduced in the latest update.

**Comment by No3371** [comment]
Can confirm It's the image download option.

**Comment by deathau** [comment]
I think I might've fixed this by adding better support for `pre` as code blocks in this commit: https://github.com/deathau/markdownload/commit/5fb11ae8cf2afff94bb710f19c47268ad56ce646
