### ISSUE TITLE
{pagetitle} with '/' downloads markdown file in a subfolder

### ISSUE THREAD

**Issue by pagkly** [deathau/markdownload#63]
# {pagetitle} with '/' downloads markdown file in a subfolder
example url with this problem:
https://www.investopedia.com/terms/p/price-earningsratio.asp which has page title
'Price-to-Earnings Ratio – P/E Ratio'

**Comment by movermeyer** [comment]
I have confirmed that this can be reproduced.

---

Ref: https://github.com/parshap/node-sanitize-filename/blob/master/index.js for how to sanitize filenames.

**Comment by movermeyer** [comment]
Just by reading the code, I think the offending line is 

https://github.com/deathau/markdownload/blob/3361645257253856e320de494136cbf371d595e2/src/background/background.js#L703

Where it splits the result by `/` before formatting each segment independently, then joins them all back together with `/`.

Note: This pattern happens at least 4 places in the code, so they probably all need to be changed.

**Comment by movermeyer** [comment]
Ref: https://github.com/parshap/node-sanitize-filename/blob/master/index.js for how to sanitize strings that are destined for filenames. (and to see all the other page titles that will cause issues by not doing sanitization correctly.

ie. `illegalRe` in `generateValidFileName` is insufficient???
