### ISSUE TITLE
Port to Safari

### ISSUE THREAD

**Issue by deathau** [deathau/markdownload#7]
No idea if there's even demand for this, as I haven't heard anything.

At first blush, it seems a bit more work to convert for Safari than between chromium/firefox
There is some guidance from Apple here: https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/SafariExtensionsConversionGuide/Chapters/Chrome.html

**Comment by dxcore35** [comment]
With new extension it should be done for Safari as well. In new Big Sur and Safari extensions become somewhat big thing. Not sure if apple make it easier to convert Chrome extensions.

**Comment by deathau** [comment]
It is a bit easier now, and I do have it mostly working at the moment, but I need to take some time to properly test it.

There's also the matter of cost. To release a Safari extension, I need to pay for an Apple developer license. For this reason, I'm considering charging for this extension. Just the minimum, and it feels weird to be charging for something that is free on every other platform, but such is the price of dealing with Apple.

Do you have any thoughts on this? Would you be willing to pay for the Safari extension?

**Comment by dxcore35** [comment]
Of course! But calculate price that it will be reasoanble for you to cover all cost and have something for coffee....
Also consider when you pay for Apple developer account you can infinite number of apps for that price.

Your extension is gem. It is true, the apple sheeps will pay :)

**Comment by oashour** [comment]
I would love to have this on Safari and would pay for it. I understand the cost of doing business with Apple and that you have to recoup the cost.

My workflow currently entails opening a link in chrome and using the extension from there, which is a pain to deal with.

P.S. thank you for all the Obsidian plugins!

**Comment by zachdaniel** [comment]
This would be great :)

**Comment by kerhbal** [comment]
I'd love to see this ported to safari, and will pay for it, the price to deal with apple...

**Comment by tokeriis** [comment]
Oh yeah, this would be nice for any markdown workflow.

**Comment by mdbraber** [comment]
@deathau possibly start a Github sponsor-thing so people can chip in to make this happen?

**Comment by mdbraber** [comment]
@deathau thanks for building this! It seems that "Download images" is not supported - is this a problem with Safari?

**Comment by deathau** [comment]
@mdbraber Yeah, I haven't been able to figure out a workaround yet. You reminded me that I needed to create the issue to track that, though (#46)

**Comment by jaredosborne** [comment]
Hey! Just grabbed this app from the apps store - happy to pay you a few $$. However it's not installing as an app. I just get the following popup, but the button doesn't work. And the extension isn't showing up in prefernces>extensions. 
https://share.getcloudapp.com/jkueXwz7

**Comment by deathau** [comment]
@jaredosborne I noticed in my testing, too, that the button didn't seem to do anything, but it _did_ show up in the Safari extensions.

Not sure what's up with this. What version of MacOS / Safari are you on?

**Comment by jaredosborne** [comment]
Safari 14.0.2
Big Sur 11.1

Haven't rebooted system, but just shut and reopened safari and same. Extension not showing.

**Comment by jeam-github** [comment]
Same problem - does not seem to install. The little installation window opens but the button labelled "Quit and Open Safari Extensions Preferences..." (what does this text actually mean?? - quit what?) does not appear to do anything (and the extension does not appear in the Extensions list in Safari, nor is it added to the displayed Safari extensions). Tried quitting Safari, rebooting system (Big Sur 11.4)

**Comment by deathau** [comment]
I'm really not sure why it's not appearing in the extensions list

The way Apple have us developing Safari extensions is somewhat confusing: They exist as _part_ of a desktop mac app. In this case the mac app is just the default template provided by Apple: A window with the icon and a button to quit the app and open safari extension preferences so you can enable the extension. So to answer your question, that's what the button does: quits the desktop mac app whose only available action is to quit. It's just a delivery mechanism for the extension.

As for why the extension is not showing up in safari itself, that's the actual issue here, and I'm kinda clueless, to be honest. If I had to guess, it would be some security related thing on Big Sur (and up) and my poor aging mac mini refuses to upgrade.

I'll do some more digging, but at the moment I don't have a solution.

**Comment by jeam-github** [comment]
Many thanks for the speedy reply and explanation of the mysterious wording in the button! 

I look forward to a fix in due course - meanwhile the FireFox version seems fine but I find it tiresome to swap out of Safari all the time.

Cheers
Jim (in Wellington, not so far from Melbourne really and free, so far, of the virus)

**Comment by Odroid-Dude** [comment]
I'm having this issue on Mojave with Safari 12, so it's not a Big Sur thing.
Also can't see how to request a refund for the thing I bought that doesn't work.

**Comment by deathau** [comment]
Damn. I'm stuck on Catalina (is Mojave before or after? I hate this naming scheme). I genuinely wonder how I can get more information about this issue...

As for refunds, I'm not familiar with the process, but from what I can tell on a quick Google search you actually have to go through apple itself? https://blog.supereasyapps.com/mac-app-store-refund-in-6-steps-how-to-get-a-refund-for-any-macos-app

I tried looking in my developer portal and could not see anything to do with issuing refunds. It just doesn't seem like a thing it's possible for me to do from my end. Even as a dev, you give up a lot of control to Apple when using their ecosystem.

**Comment by Odroid-Dude** [comment]
Mojave is 10.14
I'd rather the working extension than a refund 😉

**Comment by jeam-github** [comment]
Agreed. I would much rather have the extension fixed than a refund (which I have not even attempted), hoping a fix will appear soon!

**Comment by Odroid-Dude** [comment]
I poked around for a way to manually install the extension but didn't find anything in obvious locations

**Comment by deathau** [comment]
@jeam-github and @Odroid-Dude I'm going to close this issue (as, to my mind, the port to Safari is "complete") and replace it with #76 (for Big Sur) and #111 (for Mojave). Please go subscribe to those issues and let me know if you figure anything out.
