### ISSUE TITLE
"Copy Tab URL as Markdown Link" as a Keyboard Shortcut

### ISSUE THREAD

**Issue by Lorentz-Ipsum** [deathau/markdownload#72]
**Feature request**

Firefox: Add the posibility to map a keyboard shortcut to the "Copy Tab URL as Markdown Link" feature.

---

It is really useful to have this functionality, because many times I don't want to save the whole page, but only the link.
However, having to right-clic on the web or the tab and go through all the settings seems unnecesary.

**Comment by quintrino** [comment]
`Copy Tab URL as Markdown Link` and `Copy Tab as Markdown` as keyboard shortcuts would be amazing.

**Comment by AB1908** [comment]
Strongly agree with this one. Use tridactyl as well so it feels jarring in my workflow.

**Comment by quintrino** [comment]
I've added a PR(https://github.com/deathau/markdownload/pull/74) for copy Tab as Markdown keyboard shortcut, but if that's approved it might be really really easy to add Copy Tab URL as Markdown Link too. The PR might also need refactoring though.

**Comment by deathau** [comment]
This has been implemented, and the default shortcut is Alt+Shift+L
