### ISSUE TITLE
I can not install this extension on both chrome and edge

### ISSUE THREAD

**Issue by erichua** [deathau/markdownload#80]
I can not install this extension on both chrome and edge. it always reports that Couldn't move extension directory into profile.

**Comment by speedypard** [comment]
I also have the same problem.

https://user-images.githubusercontent.com/24541350/125290207-a6c9d280-e352-11eb-8a3c-69d3f6c82009.mp4

I also tried to install from local but don't work, either.


https://user-images.githubusercontent.com/24541350/125290928-6b7bd380-e353-11eb-87f2-233016da35aa.mp4

**Comment by deathau** [comment]
That second video gave me the error I needed to track this down. Apparrently the latest version package was missing the icons folder! No idea how I missed that.
I've submitted a new version to the firefox/edge/chrome stores, so hopefully they will be approved before too long.
In the meantime, you should be able to manually install this one: https://github.com/deathau/markdownload/releases/tag/3.0.1

**Comment by speedypard** [comment]
Thanks, installing manually is work now.
