### ISSUE TITLE
Feature Request: Add origin source URL

### ISSUE THREAD

**Issue by einverne** [deathau/markdownload#84]
I'm coming from the markdown clipper, I noticed that when I use the markdown clipper, there is an additional source URL in the bottom of the markdown file. However, when I use the makdownload extension, I cannot found the origin source.

I'd like to open PR if someone needs this too.

**Comment by deathau** [comment]
If you check the options of this plugin, you can add the source url to either the start or end if you so wish. Just make sure to enable "Append front/back template to clipped text" and fill out the templates as you wish.

**Comment by einverne** [comment]
Oh, thank you for the quick response. There are plenty of options, it is great. Thank you again for your great work.
