### ISSUE TITLE
Export LaTeX

### ISSUE THREAD

**Issue by domkm** [deathau/markdownload#85]
This extension is great, thanks for writing and maintaining it!

The one issue I'm running into is that it doesn't properly handle math. Instead of converting equations to LaTeX, it either omits them entirely or converts them to plaintext (for example, what should be `$n^2$` is output as `n2`).

**Comment by hverrill** [comment]
Would appreciate this as well. Perhaps `$$n^2$$` in addition to `$n^2$`?
