### ISSUE TITLE
Extension stuck at loading throwing TypeError: dom.head is null

### ISSUE THREAD

**Issue by mobedoor** [deathau/markdownload#87]
Hello. Extension does not work with the following [page](https://forums.fuwanovel.net/topic/5890-steinsgate-8-bit/)
Inspecting the addon showed the following.

> Uncaught (in promise) TypeError: dom.head is null
    getArticleFromDom moz-extension://8bd2b42c-240a-4607-a68a-6303d08732f3/background/background.js:653
    getArticleFromContent moz-extension://8bd2b42c-240a-4607-a68a-6303d08732f3/background/background.js:674
    downloadMarkdownFromContext moz-extension://8bd2b42c-240a-4607-a68a-6303d08732f3/background/background.js:713
    async* moz-extension://8bd2b42c-240a-4607-a68a-6303d08732f3/background/background.js:589

**Comment by jeam-github** [comment]
Same problem - does not install. The little installation window opens but the button labelled "Quit and Open Safari Extensions Preferences..." (what does this text actually mean?? - quit what?) does not appear to do anything (and the extension does not appear in the Extensions list in Safari, nor is it added to the displayed Safari extensions). Tried quitting Safari, rebooting system (Big Sur 11.4); did not help.

**Comment by ckoys** [comment]
> Same problem - does not install. The little installation window opens but the button labelled "Quit and Open Safari Extensions Preferences..." (what does this text actually mean?? - quit what?) does not appear to do anything (and the extension does not appear in the Extensions list in Safari, nor is it added to the displayed Safari extensions). Tried quitting Safari, rebooting system (Big Sur 11.4); did not help.

same for me...
