### ISSUE TITLE
Images won't download if I specify a subfolder inside Downloads/ to store MarkDownload clips

### ISSUE THREAD

**Issue by reflekteur** [deathau/markdownload#89]
Probably related to #78 

I've had this issue for quite some time now. Tested with all other extensions turned off. 

- If I download the .md into the default Downloads/ folder, then the images are saved as well.
- If I specify a subfolder, the downloads show an error ('can't download'). 
- If I specify a subfolder, but turn off the images option, then it saves into a subfolder just fine.

**Comment by wenchengxucool** [comment]
me2
