### ISSUE TITLE
What exact meta tags are supported?!

### ISSUE THREAD

**Issue by 6-AND-9** [deathau/markdownload#94]
Hello,

I love your extension, it allows me to clip webpages for Obsidian and works great. 

There's one issue, though: I can't figure out which exact meta tags are supported, aside from the ones listed here. Is there a list somewhere?

For example, I am trying to find a meta tag that will allow me to insert the top level domain of a website i.e. from a baseURI of https://www.bbc.com/world/somenews.html to obtain only bbc.com. Is this possible, and with which exact meta tag?

**Comment by iaeiou** [comment]
Hi there,

lists of meta tags are available online here and there:

- https://www.w3schools.com/tags/tag_meta.asp
- https://developers.google.com/search/docs/advanced/crawling/special-tags
- https://gist.github.com/lancejpollard/1978404

Is anyone available to make tests of the most relevant tags?

**Comment by deathau** [comment]
In the extension options, I have a list of custom text tags that are supported. These do include some url informations such as baseURI.
I also mention that I support any other meta tags that are on the page you're clipping, which is _highly_ dependent on the page.

For example, you mention bbc.com, so I clicked on a random news article there and checked the source for available meta tags:
![image](https://user-images.githubusercontent.com/1421840/204954922-42a21b4b-2afc-407b-8a08-efed796b77f0.png)
This means you could, for example, use `{og:description}` to output `A panel finds Cyril Ramaphosa abused his position in the handling of a theft from his farm.`, or `{twitter:site}` to get `@BBCWorld`. It depends on what meta tags are available on the website you are clipping from.
