### ISSUE TITLE
Endless loading of the icon menu

### ISSUE THREAD

**Issue by mike2003** [deathau/markdownload#96]
After clicking the mouse, nothing happens, it just hangs there.
https://i.imgur.com/bt1523V.jpg

**Comment by dada-man** [comment]
Same here. I've tried the extension in Vivaldi (primary) and official Chrome and they both give the same result: both the toolbar pop-up and the context menu options are completely unresponsive. Bummer for my Obsidian workflow.

**Comment by rjachuthan** [comment]
I am having the same issue as well. Tested on Firefox and Brave browser.

**Comment by deathau** [comment]
If anyone is still having this issue, please open a new issue with the url you are attempting to clip. Also, if possible, check the developer console for errors.
