### ISSUE TITLE
Custom meta properties are not parsed (for example og:image)

### ISSUE THREAD

**Issue by lenamio** [deathau/markdownload#99]
According to documentation template elements such as {og:image} can be used. However, its not replaced with actual meta property.
I think the problem is that `meta[name][content]` selector is used when parsing. But it should probably be `meta[property][content]`. At least a couple of pages I've checked use this syntax and here is an exmple from facebook docs: https://developers.facebook.com/docs/sharing/webmasters?locale=en_EN#markup-example

**Comment by east4ming** [comment]
I had the same problem

**Comment by jurassicparkin** [comment]
I'd also love to know the solution to this. Thanks!
